{"name": "Ошибка авторизации при неверных учетных данных", "status": "passed", "description": "Проверяет, что сервер возвращает ошибку при попытке входа с некорректными данными.", "steps": [{"name": "Отправляем запрос с неверным email и паролем", "status": "passed", "start": 1733135180765, "stop": 1733135181334}, {"name": "Проверяем, что сервер возвращает ошибку авторизации", "status": "passed", "start": 1733135181334, "stop": 1733135181334}], "start": 1733135180765, "stop": 1733135181335, "uuid": "dd0b15b6-76b9-482c-bb0f-c94d080993fa", "historyId": "26496ec2696525fd13cd78afd98aa8e2", "testCaseId": "26496ec2696525fd13cd78afd98aa8e2", "fullName": "tests.test_login_user.TestUserAuthentication#test_invalid_user_login", "labels": [{"name": "story", "value": "Проверка успешного и неуспешного входа в систему"}, {"name": "feature", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "MacBook-Air-Regina.local"}, {"name": "thread", "value": "8533-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}